#!/usr/bin/env python3
"""plot-fig9-a3-jsa.py -- JSA redraws of the app10_search anomaly pair,
Figure_9.pdf (fig:anomaly, c-abi-cgroup) and Figure_A3.pdf (fig:a3,
ebpf-core-cgroup).

The pre-rework PDFs came from the exploratory plot-cross-environment.py
panels: 975 pt wide with an 11 pt suptitle and 9 pt titles, which the
manuscript's \\widefig downscale prints at ~5.5 pt -- under the 7 pt floor.
This renderer reuses that script's own load_aggregate_means() / build_stats()
(imported via importlib -- the filename is not a valid module name) so the
Kruskal-Wallis omnibus is computed by the same code, then only re-geometrys
the panels to jsa_style: 516 pt wide, statistical-outcome-only panel titles
("metric KW sig (p=...)"), no suptitle (the caption names variant and
workload).

The aggregate-means.tsv input is regenerated by make-aggregate-means.py from
the banked per-rep portable.tsv captures -- the same adapter the F7
renderers use. The KW p-values this prints are cross-checked against the
pre-rework figure's panel titles before writing; a mismatch means the
aggregation drifted and the script refuses to emit.

    python3 bench/plot/make-aggregate-means.py results/p2-15metric-xdeploy-1of3
    python3 bench/plot/plot-fig9-a3-jsa.py results/p2-15metric-xdeploy-1of3 \
        --out figs
"""
from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import jsa_style as style  # noqa: E402

_PLOT_DIR = Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location(
    "plot_cross_environment", _PLOT_DIR / "plot-cross-environment.py")
xenv = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(xenv)

WORKLOAD = "app10_search"
TARGETS = {"v2.1": "Figure_9.pdf", "v3.3": "Figure_A3.pdf"}

#: KW p-values printed on the pre-rework figures' panel titles, per variant
#: and metric. Used as an aggregation-drift check only: if the recomputed
#: omnibus disagrees, the redraw would change a printed number and the ground
#: rule says stop, not emit.
BANKED_P = {
    "v2.1": {"netp": 0.406, "nets": 0.416, "blk": 1.71e-12,
             "mbw": None, "llcmr": 4.96e-08, "llcocc": 4.45e-10,
             "cpu": 3.77e-13},
    "v3.3": {"netp": None, "nets": None, "blk": 9.19e-14,
             "mbw": None, "llcmr": 7.26e-09, "llcocc": 6.08e-05,
             "cpu": 1.21e-09},
}


def check_against_banked(variant: str, stats_df) -> list[str]:
    """Compare recomputed KW p-values with the pre-rework panel titles."""
    problems = []
    for metric, banked in BANKED_P[variant].items():
        row = stats_df[(stats_df["variant"] == variant)
                       & (stats_df["workload"] == WORKLOAD)
                       & (stats_df["metric"] == metric)]
        p = row["kw_p"].iloc[0] if not row.empty else float("nan")
        if banked is None:
            if np.isfinite(p):
                problems.append(f"{variant}/{metric}: banked n/a, got p={p:.3g}")
        elif not np.isfinite(p):
            problems.append(f"{variant}/{metric}: banked p={banked:.3g}, got n/a")
        elif abs(p - banked) / banked > 0.01:
            problems.append(
                f"{variant}/{metric}: banked p={banked:.3g}, got p={p:.3g}")
    return problems


def render(df, stats_df, variant: str, out: Path) -> None:
    metrics = xenv.METRICS
    envs = [e for e in xenv.DEPLOY_ORDER if e in set(df.env)]
    ncols, nrows = 4, 2
    width = style.TEXT_WIDTH
    height = 2.9
    fig, axes = plt.subplots(nrows, ncols, figsize=(width, height),
                             squeeze=False, layout="constrained")
    for i, metric in enumerate(metrics):
        ax = axes[i // ncols][i % ncols]
        samples = xenv._samples_by_env(df, variant, WORKLOAD, metric, envs)
        present = [e for e in envs if e in samples and len(samples[e]) > 0]
        row = stats_df[(stats_df["variant"] == variant)
                       & (stats_df["workload"] == WORKLOAD)
                       & (stats_df["metric"] == metric)]
        sig = row["kw_signif"].iloc[0] if not row.empty else "n/a"
        kw_p = row["kw_p"].iloc[0] if not row.empty else float("nan")
        title = f"{metric}  KW {sig}"
        if np.isfinite(kw_p):
            title += f"  (p={kw_p:.3g})"
        ax.set_title(title, fontsize=style.TITLE)
        if not present:
            ax.set_xticks([])
            ax.set_yticks([])
            continue
        bp = ax.boxplot([samples[e] for e in present], orientation="horizontal",
                        showfliers=False, patch_artist=True)
        for patch in bp["boxes"]:
            patch.set_facecolor("#cfd8dc")
            patch.set_alpha(0.7)
        ax.set_yticks(list(range(1, len(present) + 1)))
        ax.set_yticklabels(present, fontsize=style.BODY)
        ax.tick_params(axis="x", labelsize=style.ANNOT)
        ax.set_xlabel("value", fontsize=style.BODY)
    for j in range(len(metrics), nrows * ncols):
        axes[j // ncols][j % ncols].axis("off")

    spec = style.FigSpec(width, height, f"fig:anomaly:{variant}")
    w, h = style.save(fig, out / TARGETS[variant], spec)
    plt.close(fig)
    print(f"wrote {out / TARGETS[variant]} ({w:.2f} x {h:.2f} in)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("campaign_dir", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--alpha", type=float, default=0.05)
    args = ap.parse_args()

    tsv = args.campaign_dir / "aggregate-means.tsv"
    if not tsv.exists():
        sys.exit(f"{tsv} missing -- run make-aggregate-means.py first")
    style.apply()
    df = xenv.load_aggregate_means(tsv)
    df = df[(df["workload"] == WORKLOAD) & (df["stage"] == "solo")]
    variants = sorted(TARGETS)
    envs = [e for e in xenv.DEPLOY_ORDER if e in set(df.env)]
    stats_df = xenv.build_stats(df, variants, envs, [WORKLOAD],
                                xenv.METRICS, args.alpha)

    problems = []
    for v in variants:
        problems += check_against_banked(v, stats_df)
    if problems:
        for p in problems:
            print(f"DRIFT: {p}", file=sys.stderr)
        sys.exit("recomputed KW disagrees with the banked figure titles; "
                 "refusing to emit (ground rule: flag, don't silently emit)")

    args.out.mkdir(parents=True, exist_ok=True)
    for v in variants:
        render(df, stats_df, v, args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
